### ISSUE TITLE
project doesn't run on MacOS

### ISSUE THREAD

**Issue by eriknyk** [ruslanys/sample-spring-boot-netty#3]
I'm getting this error trying to run on MacOS (Mojave)
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-06-19 00:24:11.992 ERROR 68738 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpServer' defined in file [/Users/erik/Sandbox7/sample-spring-boot-netty/build/classes/kotlin/main/me/ruslanys/web/HttpServer.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [me.ruslanys.web.HttpServer]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at me.ruslanys.ApplicationKt.main(Application.kt:10) [main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [me.ruslanys.web.HttpServer]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 17 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:55) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:52) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at me.ruslanys.web.HttpServer.<init>(HttpServer.kt:23) ~[main/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_172]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_172]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	... 36 common frames omitted
Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:177) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61) ~[netty-all-4.1.21.Final.jar:4.1.21.Final]
	... 37 common frames omitted

:bootRun FAILED

```

the most interesting error line is this one:

```
Caused by: java.lang.IllegalStateException: Only supported on Linux
```

Any thought?
Best Regards.

**Comment by ruslanys** [comment]
Hm. That's interesting. But yes, the repository itself is oriented to work on Linux servers. So, you can just wrap it into Docker container and run on MacOS inside the container.

If you want to use it on MacOS, at the `HttpServer` (https://github.com/ruslanys/sample-spring-boot-netty/blob/master/src/main/kotlin/me/ruslanys/web/HttpServer.kt) change `Epoll` to `Nio`, so:

* `EpollEventLoopGroup` to `NioEventLoopGroup`
* `EpollServerSocketChannel` to `NioServerSocketChannel`

So, Epoll itself is Linux OS capabilities.

**Comment by eriknyk** [comment]
Thanks @ruslanys

**Comment by cardosomarcos** [comment]
thanks @ruslanys (:
